### PR TITLE
Fixes libEGL and libGLESv2.so

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by jlandure** [comment]
Hi @lygstate 

Do you have documentation on how to generate `swiftshader/libEGL.so` and `swiftshader/libGLESv2.so`? Thanks for your work. 🙌

**Comment by lygstate** [comment]
@jlandure  I am not generating the file:(
I downloading https://github.com/Zenika/alpine-chrome/raw/ef108e6976c8f0a929b0c18ecf7d953b17111187/with-webgl/prebuild/chromium-80.0.3987.149-r0.apk

And then extract it with 7zip, then I will got the swiftshader/libEGL.so and swiftshader/libGLESv2.so

**Comment by jlandure** [comment]
👌  FYI, I've found a similar issue here: https://gitlab.alpinelinux.org/alpine/aports/issues/10920

**Comment by jlandure** [comment]
Thanks @lygstate I've updated this version `with-webgl` tag
https://hub.docker.com/repository/docker/zenika/alpine-chrome/tags?page=1
https://github.com/Zenika/alpine-chrome/tree/master/with-webgl
It works well. Thanks again.

**Comment by jlandure** [comment]
There is a question for you here: #52

**Comment by jlandure** [comment]
@all-contributors please add @lygstate for code and ideas

**Comment by jlandure** [comment]
@all-contributors please add @lygstate for question

**Pull request closed without merging**
