### PR TITLE
add `with-chromedriver` and `with-selenoid`

### PR DESCRIPTION
**Pull request by Trane9991**
Hey!
I faced the same issue as in #48.
Edge repository of Alpine package has chromedriver 84 now which is incompatible with chromium 83 and `apk` wouldn't let me install chromedriver 83.

So I decided to do what you suggested in the #48 and add `with-chromedriver` tag.

But my use-case is a bit deeper, I'm using the https://github.com/aerokube/selenoid (you can find more details here https://github.com/aerokube/selenoid/issues/966), so I decided this might be useful for someone else and added the `with-selenoid` tag as well.

Let me know what do you think!

### CODE REVIEW

**Comment by jlandure** [comment]
Hi @Trane9991 

Thanks for the work! Great ideas 💡  
I will check that in the coming days and create the tags as needed! 🙌 

I invite you to create a [Thank you bug request](https://github.com/Zenika/alpine-chrome/issues/new?template=03_thanks.md) to feature your usecase and company using this image 👍

**Review by jlandure — APPROVED** [review]

**Comment by jlandure** [comment]
Hey @Trane9991 👋 

Thanks for your contribution. 👍 
I want to apologize for the delay 😊 
Feel free to add other contributions during this Hacktoberfest month. 💚

**Comment by jlandure** [comment]
@all-contributors please add @Trane9991for code

**Comment by jlandure** [comment]
@all-contributors please add @Trane9991 for code

**Comment by jlandure** [comment]
I think you could add some example to document your features. 😊 
How to use this image with the 2 new tags `with-chromedriver` and `with-selenoid`?
Thanks 👍

**Comment by jlandure** [comment]
Hey @Trane9991 
You can find the news tags [here](https://hub.docker.com/repository/docker/zenika/alpine-chrome/tags?page=1) 🎉 
* `with-selenoid`, `85-with-selenoid`, `85-with-selenoid-1.10`
* `with-chromedriver`, `85-with-chromedriver`, `85-with-chromedriver-85`

Please tell me if it fits your needs. 👍 
Again thank you! 💚

**Comment by Trane9991** [comment]
> I think you could add some examples to document your features. 😊
> How to use this image with the 2 new tags `with-chromedriver` and `with-selenoid`?
> Thanks 👍

Hey, thanks!
Sure, will do that!

**Pull request merged**
