### PR TITLE
Update playwright to latest version

### LINKED ISSUE #126: ⬆️ Update Playwright with the latest version
**Context**

The example are done using Playwright 1.0.2
The latest version is 1.4.2. [See here for more info](https://github.com/microsoft/playwright/releases)

### PR DESCRIPTION
**Pull request by mecm1993**
Closes #126

### CODE REVIEW

**Comment by jlandure** [comment]
Hi @mecm1993 👋 

Thanks for your contribution. 💚 
Did you test [the playwright example](https://github.com/Zenika/alpine-chrome/tree/master/with-playwright)? 👍

**Comment by mecm1993** [comment]
Yes, I did the test, I forgot to post the evidence.

**Comment by jlandure** [comment]
Ok then! Thanks for the update. 👍

**Comment by jlandure** [comment]
@all-contributors please add @mecm1993 for code

**Pull request merged**
