### PR TITLE
WebGL support

### PR DESCRIPTION
**Pull request by pxlrbt**
Added two directories with webgl support. One is a prebuilt version since building the image takes more than a day. The other one includes the single build steps for reference if a newer version is needed and needs to be patched again.

The final docker image can be downloaded and tested from here, before integrating the PR: https://hub.docker.com/r/pxlrbt/alpine-chrome/tags

### CODE REVIEW

**Comment by lygstate** [comment]
There is no need to place chromium-80.0.3987.149-r0.apk here, we just need the webgl SO files that's install -Dm755 swiftshader/libEGL.so "$pkgdir"/usr/lib/$pkgname/swiftshader/libEGL.so
	install -Dm755 swiftshader/libGLESv2.so "$pkgdir"/usr/lib/$pkgname/swiftshader/libGLESv2.so

**Comment by pxlrbt** [comment]
@lygstate I tried it by copying the files you mentioned but with no success. Only adding the lines to the APKBUILD and recompiling chrome worked in my case.
Could you explain your solution?

**Comment by lygstate** [comment]
Maybe I forget some deps?

**Comment by pxlrbt** [comment]
Just to get it right: You only copied the Swiftshader files to `/usr/lib/chromium`and it worked? That's what I tried first. With the second try I fetched the current package from aports, added the lines you mentioned and rebuilt chromium.

**Comment by lygstate** [comment]
Oh, Imeans copy the Swiftshader files from the apk that you build, no copied from other packages.

**Comment by pxlrbt** [comment]
Yes, I think that was what I did. So you rebuilt the chromium package and extracted swiftshader files from the generated APK? How can I extract these files? Sorry, I'm not that experiences with building packages.

**Comment by lygstate** [comment]
Just to use 7zip to unpack it

**Comment by lygstate** [comment]
refer to #51

**Comment by jlandure** [comment]
Hi @pxlrbt 
Thanks again for your work! I've created the new `web-gl` tag
https://hub.docker.com/repository/docker/zenika/alpine-chrome/tags?page=1
https://github.com/Zenika/alpine-chrome/tree/master/with-webgl
It works well. Thanks again and feel free to check it out.

I've created 2 issues to discuss:
#52 and #53

**Comment by jlandure** [comment]
@all-contributors please add @pxlrbt for code and ideas

**Pull request closed without merging**
