### PR TITLE
add branch with-puppeteer-cn to support for Chinese,Janpanse and Korean language site.

### PR DESCRIPTION
**Pull request by huhai463127310**
You can use [huhai463127310/alpine-chrome:with-puppeteer-cn](https://hub.docker.com/r/huhai463127310/alpine-chrome) for Chinese,Janpanse and Korean language support.

The following command will take a screenshot for m.baidu.com (the most popular search engine in China), and save the image to `./screentshot.png`.

### CODE REVIEW

**Comment by jlandure** [comment]
Hi @huhai463127310 👋 
Thanks for your feedback and your first contribution 👍
To understand, `with-puppeteer-cn/font/wqy-microhei.ttc` cannot be downloaded from a `apk add` command ?
I will test the changes tomorrow (CEST time).

**Comment by huhai463127310** [comment]
Thanks for your reply, and it’s a good idea use *apk add* command to replace copy files. Copying files is convenient when I test building with no network cost for downloading font files and I’m sure it works. I will try your idea.

**Comment by jlandure** [comment]
Hi @huhai463127310 👋 
I have some news for you!

# Test 🐛 
I've tested and reproduced the error.
I've tried [this alpine package](https://pkgs.alpinelinux.org/package/edge/testing/x86/wqy-zenhei) and seems to work.

This package add 17,6 MB so I prefer to add this package directly in the `with-node` version
```
1902d188ebfb        10 seconds ago      /bin/sh -c apk add --no-cache -X http://dl-c…   17.6MB              
```


# What's next? 📝 
- Can you validate the temporarily new image `zenika/alpine-chrome:with-puppeteer-cn` using this command?
```
docker container run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer-cn node src/pdf-cn.js
```
- If the result is ok for you, I will push the changes (code and example using `m.baidu.com`) directly on master et close your PullRequest if you don't mind.

Are you ok with theses steps? 👍

**Comment by huhai463127310** [comment]
Hi. @jlandure 
1. Could you paste your test command and error message ? I have tested building and running and it worked well before I started the PullRequest.

    You can run this command  at anywhere path for running test, and the screenshot.png will output to current directory.
```
  docker run -it --rm  -v $(pwd):/home/chrome --cap-add=SYS_ADMIN huhai463127310/alpine-chrome:with-puppeteer-cn node src/screenshot.js
```
2. Where is the `src/pdf-cn.js` in your command '`docker container run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer-cn node src/pdf-cn.js`'?

**Comment by jlandure** [comment]
Hi @huhai463127310 

Here is the test `pdf-cn.js`.
Can you try and validate the result using `docker container run -it --rm -v $(pwd)/src:/usr/src/app/src --cap-add=SYS_ADMIN zenika/alpine-chrome:with-puppeteer-cn node src/pdf-cn.js` ?

```
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch({
    bindAddress: "0.0.0.0",
    args: [
      "--headless",
      "--disable-gpu",
      "--disable-dev-shm-usage",
      "--remote-debugging-port=9222",
      "--remote-debugging-address=0.0.0.0"
    ]
  });
  const page = await browser.newPage();
  await page.setViewport({ width: 412, height: 732 });
  await page.goto("https://m.baidu.com", { waitUntil: "networkidle2" });
  await page.screenshot({ path: "src/baidu.png" });
  await browser.close();
})();
```

**Comment by huhai463127310** [comment]
Hi. @jlandure 
I have validated the result with your command. It works well on my environment. I tested `https://m.baidu.com`, `https://www.yahoo.co.jp/` and `https://www.naver.com/`  for Chinese,Janpanse and Korean language site.

**Comment by jlandure** [comment]
Thanks @huhai463127310 for the work and helping me!
Now we have a good `with-node` and `with-puppeteer` image working for asian language. 🎉

**Comment by huhai463127310** [comment]
> Thanks @huhai463127310 for the work and helping me!
> Now we have a good `with-node` and `with-puppeteer` image working for asian language. 🎉

Thanks for your works.

**Comment by jlandure** [comment]
@all-contributors please add @huhai463127310 for code and ideas

**Pull request closed without merging**
